### ISSUE TITLE
Can't found the app

### ISSUE THREAD

**Issue by ico0018** [shamspias/customizable-gpt-chatbot#14]
Hi, 

I am following your instruction to run the source code. But here is an issue:

celery -A customizableGpt3Chatbot worker --loglevel=info
Usage: celery [OPTIONS] COMMAND [ARGS]...
Try 'celery --help' for help.

Error: Invalid value for '-A' / '--app':
Unable to load celery application.
The module customizableGpt3Chatbot was not found.

Anything wrong for me? Thank you.

**Comment by ico0018** [comment]
using command: celery -A config worker --loglevel=info to get the model.

But this another issue that:

django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'users.User' that has not been installed

I am trying to compile your main branch.

**Comment by jjones7** [comment]
Hey there.  I think we are trying to do the same thing.  Myself and a data engineer are working on a similar product to commercialise. We currently both work for a unicorn and are looking for collaborators on this side project.  Please let me know if you want to talk ;) 😉

**Comment by shamspias** [comment]
Sorry for the issue
There was a bug so updated the code
will update README.md soon
and also removed previous langchain and rasa code
I am updating little by little sorry for the issue.

**Comment by shamspias** [comment]
@jjones7  @ico0018 
Please wait a few days and let me update the basic code then after updating README.md I will be informed here.

**Comment by ico0018** [comment]
Thank you. Could you provide any tip for the compile? Is the main branch work?

**Comment by shamspias** [comment]
yes it's work.
I will write instructions how to.
until you have to wait please

**Comment by ico0018** [comment]
Great, Thank you. Looking for it.

**Comment by shamspias** [comment]
Thanks for your patience.
Readme is updated please check.
