### ISSUE TITLE
get_user_model

### ISSUE THREAD

**Issue by shubham184** [shamspias/customizable-gpt-chatbot#20]
```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\gptchat-env\Lib\site-packages\django\apps\config.py", line 235, in get_model
    return self.models[model_name.lower()]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'user'
```
`django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'users.User' that has not been installed`

**Comment by shamspias** [comment]
please rename the users.User to users.CustomUser
I will update the example.env

**Comment by Valengou** [comment]
You should also change it in the common.py file at the config-setting folders

**Comment by shamspias** [comment]
if anyone writes in .env the custom user model then they no longer need to change from config/settings/common.py
