### ISSUE TITLE
Mac question about Installation libcurl4-openssl-dev gcc libssl-dev -y

### ISSUE THREAD

**Issue by ivan-vilches** [shamspias/customizable-gpt-chatbot#21]
Hello, in mac is the same process for? :
In linux need to install pip install pycurl' and 'sudo install python3-dev -y

Make sure that you have the development libraries for libcurl installed on your system. You can install them by running the following command: sudo apt-get install libcurl4-openssl-dev gcc libssl-dev -y

Thanks you

**Comment by shamspias** [comment]
Please check the updated README.md 
and yes same for mac as well.
please give me feedback here because I don't test in MAC yet

**Comment by ivan-vilches** [comment]
it works on mac m1 monterrey 12.4

**Comment by shamspias** [comment]
thanks for the information
