### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'users.User' that has not been installed

### ISSUE THREAD

**Issue by ivan-vilches** [shamspias/customizable-gpt-chatbot#22]
running celery i get this:
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'users.User' that has not been installed

**Comment by shamspias** [comment]
Please check the readme.md 
and new example.env I updated the user model settings

just change users.User to users.CustomUser in your .env
