### ISSUE TITLE
running but missing chatbot UI (seeing only the fastAPI/swagger on http://127.0.0.1:8000

### ISSUE THREAD

**Issue by urbanscribe** [shamspias/customizable-gpt-chatbot#26]
1) if helpful i had to go through a few extra steps to migrate user and other data when setting up postgres

specifically 

```
python manage.py migrate

Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_celery_results, oauth2_provider, sessions, sites, social_django, users
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK

plus many other
``` 

and

`python manage.py makemigrations users`

on first setup

anyhow, 

when completed and celery running on redis and manage on postgres i get the fastAPI page (swagger) on http://127.0.0.1:8000 but no chatbot or front end.  is this supposed to be a chatbot API project (bring your own chatbot to hookup) or is the chatbot UI itslef included in the runtime?

i see the chat folders and many files so i assumed there would be a front end.  not sure what i missed.
thanks for your help

**Comment by shamspias** [comment]
Sorry for your confusion
There is no front-end here.

you can use Django admin by using /admin to upload document and train(insert into vector)
