### ISSUE TITLE
Has anyone gotten this up an running

### ISSUE THREAD

**Issue by curlybosschick** [shamspias/customizable-gpt-chatbot#28]
Mind you I am not a master at code, but familiar with most of python and can usually reverse engineer my way through things.  I am not familiar with Django yet and having issues trying to get this even to run locally on my computer.  I'm repeatedly coming across celery and django errors.  Not sure what I can do to rectify and where to go from here.  HELP!

**Comment by shamspias** [comment]
Can you write your error's here?

**Comment by curlybosschick** [comment]
I have many.  After going through many I'm currently here with the most recent error.  I was able to get through the previous one by posting into Chatgpt and then running the commands line by line.  Ultimately it started with "celery" errors and continued from there while running the requirment.txt file.

 " File "C:\Users\lia\AppData\Local\Programs\Python\Python311\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: invalid integer value "database_port" for connection option "port""

**Comment by shamspias** [comment]
> I have many. After going through many I'm currently here with the most recent error. I was able to get through the previous one by posting into Chatgpt and then running the commands line by line. Ultimately it started with "celery" errors and continued from there while running the requirment.txt file.
> 
> " File "C:\Users\lia\AppData\Local\Programs\Python\Python311\Lib\site-packages\psycopg2__init__.py", line 122, in connect conn = _connect(dsn, connection_factory=connection_factory, **kwasync) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ django.db.utils.OperationalError: invalid integer value "database_port" for connection option "port""




The port number for PostgreSQL is typically 5432, and this setting should be an integer, not a string. It seems like your code is trying to connect to the database with the port number "database_port", which is not a valid port number.

Check your Django DATABASES setting in the `settings/local.py` file or prod or stage the environment you select. It should look something like this:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': '<your_db_name>',
        'USER': '<your_db_user>',
        'PASSWORD': '<your_db_password>',
        'HOST': '<your_db_host>',
        'PORT': <your_db_port>,  # Ensure this is a valid integer, usually 5432
    }
}
```
Ensure that the value for 'PORT' is an integer. It could be that 'PORT' is being set somewhere in your code or in your environment variables as "database_port". This should be corrected to a valid port number, which by default for PostgreSQL is usually 5432.

**Comment by curlybosschick** [comment]
I'll check that, but as I said, I haven't made any changes and am running it from the script written.  Not expected errors :(

**Comment by shamspias** [comment]
You have to be setup the .env based on example.env
