### ISSUE TITLE
How can i connect with flutter ? 

### ISSUE THREAD

**Issue by Hasib74** [shamspias/customizable-gpt-chatbot#9]
Is there any API or SDK for connecting with mobile?

**Comment by shamspias** [comment]
Yes, you can,
After running the application you can find the API swagger panel by going 127.0.0.1:8000 or the address you set to run it.
you can see API documentation from it.
also can see all the parameters from 127.0.0.1:8000/redoc

Hope it will solve your issue.
Thanks.
